const tips = {
    "No (2FA Not Enabled)": `If you selected that 2FA is not enabled or you don't know, you are currently relying on a single point of failure: your password. In the modern digital world, a password alone is considered insufficient security because it can be stolen, guessed, or leaked in database breaches. Without 2FA, a hacker only needs that one string of characters to take over your life. The Change You Need: You must immediately go to the "Security" settings of your most critical accounts—specifically your primary email, banking apps, and social media—and activate Two-Factor Authentication. This adds a second layer, usually a code sent to your phone or generated by an app, ensuring that even if a hacker steals your password, they cannot enter your account without your physical device.`,
    "Don't Know / Not Offered": `If you selected that 2FA is not enabled or you don't know, you are currently relying on a single point of failure: your password. In the modern digital world, a password alone is considered insufficient security because it can be stolen, guessed, or leaked in database breaches. Without 2FA, a hacker only needs that one string of characters to take over your life. The Change You Need: You must immediately go to the "Security" settings of your most critical accounts—specifically your primary email, banking apps, and social media—and activate Two-Factor Authentication. This adds a second layer, usually a code sent to your phone or generated by an app, ensuring that even if a hacker steals your password, they cannot enter your account without your physical device.`,
    "Medium Security": `Selecting Medium, Low, or Very Low security indicates that your passwords are likely based on dictionary words, personal names, simple patterns (like "123"), or are just too short. These types of passwords are vulnerable to "brute force" attacks, where hacker software can guess millions of combinations in seconds. A "Medium" password might feel safe to you, but if it follows a predictable pattern (like "Surname@Year"), it is trivial for a computer to crack. The Advice: You need to stop creating passwords that are easy for humans to remember. A strong password should look like random noise (e.g., Xy9#mP2!L). Since you cannot remember these, you must transition to using a Password Manager tool which creates and stores high-security passwords for you.`,
    "Low Security": `Selecting Medium, Low, or Very Low security indicates that your passwords are likely based on dictionary words, personal names, simple patterns (like "123"), or are just too short. These types of passwords are vulnerable to "brute force" attacks, where hacker software can guess millions of combinations in seconds. A "Medium" password might feel safe to you, but if it follows a predictable pattern (like "Surname@Year"), it is trivial for a computer to crack. The Advice: You need to stop creating passwords that are easy for humans to remember. A strong password should look like random noise (e.g., Xy9#mP2!L). Since you cannot remember these, you must transition to using a Password Manager tool which creates and stores high-security passwords for you.`,
    "Very Low Security": `Selecting Medium, Low, or Very Low security indicates that your passwords are likely based on dictionary words, personal names, simple patterns (like "123"), or are just too short. These types of passwords are vulnerable to "brute force" attacks, where hacker software can guess millions of combinations in seconds. A "Medium" password might feel safe to you, but if it follows a predictable pattern (like "Surname@Year"), it is trivial for a computer to crack. The Advice: You need to stop creating passwords that are easy for humans to remember. A strong password should look like random noise (e.g., Xy9#mP2!L). Since you cannot remember these, you must transition to using a Password Manager tool which creates and stores high-security passwords for you.`,
    "Yearly" : `You use an account Yearly or have Forgot the Account reveals a significant "Zombie Account" risk. When you leave an account dormant for long periods, you stop monitoring it for security alerts. If that service suffers a data breach, or if a hacker guesses your credentials, they can access your data and use the account for fraud for months without you ever noticing. The Change You Need: For accounts you use yearly (like tax portals), ensure your recovery email/phone number is current so you get login alerts. For accounts you "Forgot," you must conduct a digital audit: search your email inbox for "Welcome" or "Verify" emails to rediscover these old accounts and either secure them or delete them entirely.`,
    "Forgot Account" : `You use an account Yearly or have Forgot the Account reveals a significant "Zombie Account" risk. When you leave an account dormant for long periods, you stop monitoring it for security alerts. If that service suffers a data breach, or if a hacker guesses your credentials, they can access your data and use the account for fraud for months without you ever noticing. The Change You Need: For accounts you use yearly (like tax portals), ensure your recovery email/phone number is current so you get login alerts. For accounts you "Forgot," you must conduct a digital audit: search your email inbox for "Welcome" or "Verify" emails to rediscover these old accounts and either secure them or delete them entirely.`,
    "Allow All the Time" : `Choosing "Allow All the Time" for sensitive permissions like Location or Microphone is a severe privacy error. This setting grants the app the legal and technical right to track your physical movements, listen to your environment, or access your camera even when your phone is locked in your pocket. This builds a massive, invasive surveillance profile of your daily habits that is often sold to advertisers. The Advice: Go to your phone's privacy settings immediately. Change the permission for every single app from "Allow All the Time" to "Only While Using the App." This ensures the app can function when you need it (like a map for navigation) but stops spying on you the moment you close it.`,
    "Don't Read" : `By selecting "Don't Read," you are blindly accepting terms that may be exploitative. Many free apps make money by legally forcing you to agree to sell your contact list, photos, or messages to third parties. When you click "Agree" without checking, you have legally consented to this data harvesting. The Change You Need: You do not need to read the entire legal document, but you must stop clicking blindly. Adopt the habit of "Skimming." Scroll through the policy and look for bold headings or keywords like "Data Sharing," "Third Parties," or "Marketing." If an app says it shares your personal data with "partners," pause and decide if that app is truly worth the cost of your privacy.`,
    "Memory" : `Relying on Memory or Reuse is the single most dangerous habit in cybersecurity. The human brain is incapable of remembering unique, complex strings for 50+ different accounts, which forces you to reuse passwords. If you use the same password for a low-security gaming site and your bank, a hacker breaching the game site instantly has the key to your bank account. The Advice: You must break the habit of reuse immediately. Download a Password Manager (like Google Password Manager, Bitwarden, or 1Password). Start by changing your Email and Banking passwords to unique, complex entries generated by the manager. This "compartmentalizes" your risk so that one breach does not destroy your entire digital life.`,
    "Reuse" : `Relying on Memory or Reuse is the single most dangerous habit in cybersecurity. The human brain is incapable of remembering unique, complex strings for 50+ different accounts, which forces you to reuse passwords. If you use the same password for a low-security gaming site and your bank, a hacker breaching the game site instantly has the key to your bank account. The Advice: You must break the habit of reuse immediately. Download a Password Manager (like Google Password Manager, Bitwarden, or 1Password). Start by changing your Email and Banking passwords to unique, complex entries generated by the manager. This "compartmentalizes" your risk so that one breach does not destroy your entire digital life.`,
    "Click Link" : `If your move is to "Click the Link" when you see a bank alert, you are highly susceptible to Phishing. Scammers rely on fear and urgency (e.g., "Your KYC is expired!") to make you act without thinking. Clicking that link takes you to a fake website that looks exactly like your bank, where you will unknowingly type your username and password directly to the hacker. The Change You Need: Adopt a "Zero Trust" policy for SMS links. Never, ever click a link in a text message that claims to be from a bank or government. Instead, close the message, open your official banking app separately, or call the bank's official support number to verify if the alert is real.`,
    "Click Link Prize" : `Choosing to Click or Forward a "Free Prize" email indicates a vulnerability to Social Engineering. These emails are baits designed to infect your device with malware or steal your personal data. Even worse, by forwarding it to friends, you become a "Super Spreader," validating the scam to people who trust you and putting their security at risk. The Advice: Understand that in the digital world, there is no such thing as a free, urgent prize. If an email offers you something amazing for free, it is a lie. Mark these emails as "Spam" immediately to train your email filter, and never forward them. Deleting them stops the attack chain with you.`,
    "Forward to Friends" : `Choosing to Click or Forward a "Free Prize" email indicates a vulnerability to Social Engineering. These emails are baits designed to infect your device with malware or steal your personal data. Even worse, by forwarding it to friends, you become a "Super Spreader," validating the scam to people who trust you and putting their security at risk. The Advice: Understand that in the digital world, there is no such thing as a free, urgent prize. If an email offers you something amazing for free, it is a lie. Mark these emails as "Spam" immediately to train your email filter, and never forward them. Deleting them stops the attack chain with you.`,
    "Connect Directly" : `Connecting Directly to free Wi-Fi means your data is traveling through the air unencrypted. Hackers can easily sit in the same cafe or airport with simple software and intercept everything you are sending, including session cookies, passwords, and emails (Man-in-the-Middle attack). The Change You Need: Stop trusting public networks. If you have mobile data (4G/5G), use that instead—it is much more secure. If you absolutely must use public Wi-Fi, you need to install and use a VPN (Virtual Private Network) app. This encrypts your data inside a secure tunnel, making it unreadable to anyone else on the Wi-Fi network.`,
    "No, Never Thought To" : `Answering "No" means you are flying blind regarding your public reputation. Information about you—including your home address, phone number, old photos, or court records—could be publicly accessible to recruiters, stalkers, or scammers without your knowledge. The Advice: You need to perform a self-audit. Open an "Incognito" or "Private" browser window and search for your full name, email address, and phone number. See what comes up. This will allow you to identify exposed data and take steps to remove it, such as asking websites to take down old photos or locking down your social media profiles.`,
    "Stop Logging In" : `If your strategy is to simply "Stop Logging In," you are leaving a trail of unsecured personal data across the internet. These abandoned accounts still hold your personal details, messages, and perhaps old passwords. If that service gets hacked five years from now, your data will be leaked, and you won't even know because you stopped checking the account. The Change You Need: You must adopt a "Clean House" policy. If you decide you no longer need a service (like an old shopping site or dating app), log in one last time and find the "Delete Account" or "Close Account" option in the settings. Permanently deleting the account removes your data from their servers, eliminating the risk forever.`
}

const el = document.getElementById("main-container");
const rect = el.getBoundingClientRect();


console.log("Bottom (viewport):", rect.bottom);


const bottomAbsolute = rect.bottom + window.scrollY;
console.log("Bottom (page):", bottomAbsolute);
console.log(window.innerHeight);

if(bottomAbsolute <= window.innerHeight-70) {
    document.querySelector("footer").style.cssText = `
        display: flex;
        flex-direction: row;
        position: fixed;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 60px;
        background-color: #FFFFFF;
        gap: 40px;
        color: #737373;
        box-shadow: 0 4px 6px rgba(0,0,0,0.3);
        padding-left: 15%;
        align-items: center;
        bottom: 0px;
    `;
}

let username = "";

const item = JSON.parse(localStorage.getItem("privacy_dept_username"));
if (item && new Date().getTime() < item.expiry) {
    console.log("privacy_dept_username:", item.value);
    username = item.value;
    console.log(username);
} else {
    localStorage.removeItem("privacy_dept_username");
}
console.log(username);
let loginBox = document.querySelector("#login");

if(username == null || username.trim() == "") {
    console.log("Hello");
    loginBox.innerHTML = `<button onclick="location.href='login_register.html'"><h3>Sign/Register</h3></button>`;
} else {
    loginBox.innerHTML = `<button onclick="displayLoginDiv();" style=" width:40px; background-color: #FFFFFF;"><img src="user_profile_login.png"></button>`;
}

document.addEventListener("click", function(event) {
    const loginContainer = document.getElementById("loginContainer");
    const loginBtn = document.querySelector("#login button");
    if (loginContainer && !loginContainer.contains(event.target) && !loginBtn.contains(event.target)) {
        document.body.removeChild(loginContainer);
    }
});

function displayLoginDiv() {
    if(document.getElementById("loginContainer")) {
        return;
    }

    bodyCont = document.body;

    loginContainer = document.createElement('div');
    loginContainer.setAttribute("id", "loginContainer");
    loginContainer.style.cssText =  ` display: flex;
                                    flex-direction: column;
                                    position: fixed;
                                    width: 200px;
                                    padding: 10px;
                                    top:60px;
                                    right: 10px;
                                    background-color: #FFFFFF;
                                    z-index: 10;
                                    box-shadow: 0 4px 6px rgba(0,0,0,0.3);
    `;

    usernameDiv = document.createElement('h3');
    usernameDiv.innerHTML = username;
    usernameDiv.style.cssText = "height: 20px; width: 180px; padding: 5px; margin: 0px;";
    loginContainer.appendChild(usernameDiv);

    logoutDiv = document.createElement('h3');
    logoutDiv.innerHTML = "Logout";
    logoutDiv.style.cssText = "height: 20px; width: 180px; padding: 5px; margin: 0px;";
    logoutDiv.addEventListener('click', function() {
        localStorage.removeItem("privacy_dept_username");
        location.reload();
    });
    loginContainer.appendChild(logoutDiv);

    bodyCont.appendChild(loginContainer);
}

const params = new URLSearchParams(window.location.search);

const ctx = document.getElementById('divergingChart').getContext('2d');

let label_name = JSON.parse(decodeURIComponent(params.get("labels")));
let label_data = JSON.parse(decodeURIComponent(params.get("data")));

new Chart(ctx, {
type: 'bar',
data: {
    labels: label_name,
    datasets: [{
    label: "Values",
    data: label_data,
    backgroundColor: function(context) {
        return context.raw >= 0 ? "green" : "red";
    }
    }]
},
options: {
    responsive: false
}
});

function updateGradient(color1, color2, deg) {
  const circle = document.getElementById("conio-bar");
  circle.style.background = `conic-gradient(
    ${color1} 0deg ${deg}deg,
    ${color2} ${deg}deg 360deg
  )`;
}

let val1 = params.get("points");
let val2 = params.get("total_points");

let totalBar = document.getElementById("totalPointChart");
totalBar.innerHTML = "<h2>"+ val1 + " / <br>" + val2 +"</h2>";

let color1 = (val1 > 0? "green": "red");
if( Math.abs(val1) > val2) {
    updateGradient(color1, "#a7a7a7", 360)
} else {
    val1 = Math.abs(val1);
    updateGradient(color1, "#a7a7a7", (360*val1)/val2);
}

let cnt = 1;
let tips_container = document.getElementById("tips_container");

for(let i=5; i<label_name.length; i++) {
    if(label_name[i] in tips) {
        let para = document.createElement("p");
        para.innerHTML = `<b> ${cnt}. ${tips[label_name[i]]} </b>`;
        para.style.textAlign = "justify";
        tips_container.appendChild(para);
        cnt += 1
    }    
}
