/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blood_donation_aplication;

import static blood_donation_aplication.View_Donor_Details_Frame.data1;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s
 */
public class View_Donor_Details_Frame extends javax.swing.JFrame {

    /**
     * Creates new form View_Donor_Details_Frame
     */
    public static String data1[][];
    public View_Donor_Details_Frame() {
        super("View Donor Details");
        initComponents();
        String colname[] = {"Addhar Card Number","Donor Name","Token Status"};
        View_Donor_Details vdd = new View_Donor_Details();
        vdd.getViewDonorDetails();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data1, colname));
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Blood_drop_icon_1.jpg")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adhar No.", "Donor Name", "Token Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 50, 710, 420);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood_donation_aplication/create_profile_1.png"))); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 480, 90, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood_donation_aplication/blood_donation_S5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 768);

        jMenu1.setText("Manage Profile");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood_donation_aplication/create_profile_1.png"))); // NOI18N
        jMenuItem1.setText("Edit Profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Donor");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood_donation_aplication/add_account_1.png"))); // NOI18N
        jMenuItem2.setText("Add New Donor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood_donation_aplication/clould_user_1.png"))); // NOI18N
        jMenuItem3.setText("View Donor Details");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Logout");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood_donation_aplication/user_profile_login_8.png"))); // NOI18N
        jMenuItem4.setText("Logout");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>                        

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        blood_donation_Frame bdf = new blood_donation_Frame();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        bdf.setVisible(true);
        bdf.setSize(d);
        this.dispose();
    }                                          

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        edit_profile ePro = new edit_profile("");
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        ePro.setVisible(true);
        ePro.setSize(d);
        this.dispose();
    }                                          

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Donor donor = new Donor();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        donor.setVisible(true);
        donor.setSize(d);
        this.dispose();
    }                                          

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
         View_Donor_Details_Frame Vddf = new View_Donor_Details_Frame();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        Vddf.setVisible(true);
        Vddf.setSize(d);
        this.dispose();
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1)
        {
            String adhar = (String)model.getValueAt(row, 0);
            String name = (String)model.getValueAt(row, 1);
            String token_status = (String)model.getValueAt(row, 2);

            ArrayList data = new Donor_Details_Fetcher_For_Edit().getDonorData(adhar);

            Edit_Donor_Details eddf = new Edit_Donor_Details();
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            eddf.setVisible(true);
            eddf.setSize(d);
            this.dispose();

            eddf.jTextField1.setText(adhar);
            eddf.jTextField6.setText(name);
            eddf.jTextField7.setText((String)data.get(1));
            eddf.jTextField8.setText((String)data.get(2));
            eddf.jTextArea2.setText((String)data.get(3));
            String dob = (String)data.get(4);
            String str[] = dob.split("/");
            String day = str[0];
            String month = str[1];
            String year  = str[2];
            eddf.jComboBox2.setSelectedItem(day);
            eddf.jComboBox3.setSelectedItem(month);
            eddf.jComboBox4.setSelectedItem(year);
            eddf.jTextField4.setText((String)data.get(5));
            String gender = (String)data.get(6);
            if(gender.equals("Male"))
                eddf.jRadioButton1.setSelected(true);
            if(gender.equals("Female"))
                eddf.jRadioButton2.setSelected(true);
            if(gender.equals("Other"))
                eddf.jRadioButton3.setSelected(true);
            eddf.jTextField2.setText((String)data.get(7));
            eddf.jTextField3.setText((String)data.get(8));
            eddf.jComboBox1.setSelectedItem((String)data.get(9));
            eddf.jTextField5.setText((String)data.get(10));
            eddf.jTextField9.setText((String)data.get(11));
            eddf.jTextField10.setText((String)data.get(12));
            eddf.jTextField11.setText((String)data.get(13));
            eddf.jTextField12.setText((String)data.get(14));
        }
        else
        {
            if(jTable1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(null,"Table is Empty");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please Select The Row");
            }
        }

    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Donor_Details_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Donor_Details_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Donor_Details_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Donor_Details_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Donor_Details_Frame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
